name: criando artefatos

on:
  push:

jobs:
  checkout_code:
    name: Faz checkout do código
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3.3.0
      
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ vars.DRIVER }}
        path: .
    
